app:
  mode: "local"

logger:
  log_level: "info"
  log_output: ""

db: # host=localhost user=postgres password=rootroot dbname=Aviasales port=5433 sslmode=disable
  host: "localhost"
  user: "postgres"
  password: "rootroot"
  port: 5433
  database: "Aviasales"
  migration: true

grpc:
  port: 44044
  timeout: 10h # no more than 5s if prod